
spring:
   profiles:
     active: ${profileActive}
   application:
     name: webuy-task
   freemarker:
     allow-request-override: false
     cache: false
     charset: utf-8
     content-type: text/html;charset=utf-8
     suffix: .ftl
     prefix: /job
     request-context-attribute: request
     exposeRequestAttributes: true
     exposeSpringMacroHelpers: true
     exposeSessionAttributes: true

logging:
  config: classpath:config/logback/logback-spring.xml

mybatis:
  config-location: classpath:config/mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.weweibuy.webuy.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS





