server:
  port: 9301
  security:
    user:
      name: admin
      password: ak402507979

app:
  id: ${spring.application.name}
apollo:
  meta: http://106.12.15.87:9080
  bootstrap:
    namespaces: application,sentinel


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@106.12.95.245:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}  #必须唯一
    prefer-ip-address: true     #访问路径可以显示IP地址,此为内网ip,如果server和client不在同一网段使用ip-address:配置
    ip-address: 127.0.0.1
    metadata-map:
       context-path: /actuator
       startup: ${random.int}    #needed to trigger info and endpoint update after restart
       "user.name": ${spring.security.user.name}         #These two are needed so that the server
       "user.password": ${spring.security.user.password}  #can access the protected client endpoints
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/
