server:
  port: 8401

spring:
  zipkin:
    base-url: http://106.12.95.245:9411
    enabled: true
    message-timeout: 10
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 0.3
    feign:
     enabled: true
     processor:
       enabled: true
  redis:
    timeout: 5000 # 连接超时时间（毫秒）
    database: 4 # Redis数据库索引（默认为0）
    host: 47.99.129.104  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: ak402507979 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 3 # 连接池中的最大空闲连接
        max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 2 # 连接池中的最小空闲连接
  rabbitmq:
    host: 47.99.129.104
    port: 5672
    username: user01
    password: ak402507979
    virtual-host: /message
    connection-timeout: 15000
    listener:    #监听数量
      simple:
        default-requeue-rejected: false  #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        prefetch: 1   #一次可以消费的消息,可用于限流
        concurrency: 1    #最小监听数
        max-concurrency: 5  #最大监听数
        acknowledge-mode: MANUAL  #手动应答
        retry:  #重试机制,当监听发放抛出异常后,会自动进行重新发送(重试几次后RabbitMQ,没有想那个监听发消息了)
          max-attempts: 3   #最大重试次数
          enabled: true  #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          initial-interval: 2000  #重试间隔时间（单位毫秒

      direct:
        acknowledge-mode: MANUAL
        prefetch: 1  #一次可以消费的消息,可用于限流
    publisher-confirms: true  #comfirmsCallback
    publisher-returns: true   #returnCallback
    template:
      mandatory: true    #使用returnCallback必须为true
  security:
    user:
       name: admin
       password: ak402507979

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@47.99.129.104:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}  #必须唯一
    prefer-ip-address: true     #访问路径可以显示IP地址,此为内网ip,如果server和client不在同一网段使用ip-address:配置
    ip-address: 119.3.11.116
    metadata-map:
       context-path: /actuator
       startup: ${random.int}    #needed to trigger info and endpoint update after restart
       "user.name": ${spring.security.user.name}         #These two are needed so that the server
       "user.password": ${spring.security.user.password}  #can access the protected client endpoints
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/

hystrix: #hystrix配置
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: thread
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:
        sleepWindowInMilliseconds: 20000 #断路器恢复时间
        errorThresholdPercentage: 50  #触发短路,失败百分比
  threadpool:
    default:
      coreSize: 10  #线程池大小
      maxQueueSize: 10  #最大等待队列数

feign:
  client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 2000   #请求处理的超时时间
        readTimeout: 5000  #请求连接的超时时间
  hystrix:
    enabled: true  #是否启用feign的 hystrix;不启用使用ribbon的超时控制
  compression: #Spring Cloud Feign支持对请求和响应进行GZIP压缩，以提高通信效率
      request:
        enabled:  true   # 开启对 request 请求压缩
        mime-types:
          - text/xml
          - application/xml
          - application/json    # 指定压缩格式
        min-request-size: 2048  # 压缩的最小阀值，默认 2048，超过2048 （字节） 进行压缩。
      response:
        enabled:  true  # 开启对 response 的压缩








