
spring:
   profiles:
     active: ${profileActive}
   application:
     name: webuy-support
   mail:
     default-encoding: UTF-8
     host: smtp.126.com
     port: 25
     protocol: smtp
     username: ak40250@126.com
     password: ak402507979

logging:
  config: classpath:config/logback/logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS







