server:
  port: 7001
  tomcat:
    max-threads: 10   #Spring boot自带的tomcat线程数默认值为200个
    min-spare-threads: 5    #初始化线程数

spring:
  profiles:
    active: ${profileActive}
  application:
    name: webuy-eureka

#  boot:      # 在erueka 没有想注册中心注册自己的时候使用
#    admin:
#      auto-registration: true  #客户端是否自动注 册
#      client:
#        url: http://localhost:7501
#        username: admin
#        password: ak402507979
#        instance:
#          prefer-ip: true  #客户端是否提供本机真实ip
#          service-url: http://${eureka.instance.ip-address}:${server.port}

#配置日志
logging:
  config: classpath:config/logback/logback-spring.xml


management:  #用于springBoot-Admin 健康检查
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

