server:
  port: 7001
  tomcat:
    max-threads: 10   #Spring boot自带的tomcat线程数默认值为200个
    min-spare-threads: 5    #初始化线程数

spring:
  profiles:
    active: ${profileActive}
  application:
    name: webuy-eureka
  security:
    user:
      name: admin
      password: ak402507979
#  boot:      # 在erueka 没有想注册中心注册自己的时候使用
#    admin:
#      auto-registration: true  #客户端是否自动注 册
#      client:
#        url: http://localhost:7501
#        username: admin
#        password: ak402507979
#        instance:
#          prefer-ip: true  #客户端是否提供本机真实ip
#          service-url: http://${eureka.instance.ip-address}:${server.port}


#配置日志
logging:
  config: classpath:config/logback/logback-spring.xml

---
  #dev environment
spring:
  profiles: dev

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
   # hostname: localhost  #eureka服务端的实例名称
    ip-address: 127.0.0.1
  server:
    enable-self-preservation: false  #关闭自我保护
    response-cache-auto-expiration-in-seconds: 120
    response-cache-update-interval-ms: 60000  #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
                                             #默认30s
    eviction-interval-timer-in-ms: 60000  #启用主动失效，并且每次主动失效检测间隔为10s
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #  是否从eureka上获取注册信息   false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
  #test environment
spring:
  profiles: test

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    #hostname: localhost  #eureka服务端的实例名称,
    ip-address: 47.99.129.104
  server:
    enable-self-preservation: false  #关闭自我保护,开启自我保护eureka不会注销任何微服务
    response-cache-auto-expiration-in-seconds: 120
    response-cache-update-interval-ms: 60000  #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
                                             #默认30s
    eviction-interval-timer-in-ms: 60000  # 清理间隔 启用主动失效，并且每次主动失效检测间隔为10s
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #  是否从eureka上获取注册信息   false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/

       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---





management:  #用于springBoot-Admin 健康检查
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

