server:
  port: 8888


spring:
  profiles:
    active: ${profileActive}
  application:
    name: learning-event
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/webuy_event?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
    username: user01
    password: ak402507979

logging:
  config: classpath:config/logback/logback-spring.xml


mybatis:
  type-aliases-package: com.weweibuy.webuy.learning.event.model.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件


