server:
  port: 8084
spring:
  profiles:
    active: ${profileActive}
  application:
    name: learning-es-rest
  data:
    elasticsearch:
      cluster-name: my-es
      cluster-nodes: 106.12.208.53:9300
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/learning_es?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
    username: user01
    password: ak402507979
    hikari:
      max-lifetime: 300000

     ## TODO  No operations allowed after connection closed  异常


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@122.51.171.126:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}  #必须唯一
    prefer-ip-address: true     #访问路径可以显示IP地址,此为内网ip,如果server和client不在同一网段使用ip-address:配置
    ip-address: 127.0.0.1


logging:
  config: classpath:config/logback/logback-spring.xml

mybatis:
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml

es:
  username: elastic
  password: ak402507979
  host: 106.12.208.53
  port: 9200