
spring:
  profiles:
    active: ${profileActive}
  application:
    name: learning-spring

logging:
  config: classpath:config/logback/logback-spring.xml

app:
  id: ${spring.application.name}
apollo:
  meta: http://106.12.15.87:9080

