
spring:
  profiles:
    active: ${profileActive}
  application:
    name: learning-spring
  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  config: classpath:config/logback/logback-spring.xml

app:
  id: ${spring.application.name}
apollo:
  meta: http://106.12.15.87:9080
  bootstrap:
    namespaces: application,sentinel


mybatis:
  type-aliases-package: com.weweibuy.webuy.learning.spring.model.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件
