server:
  port: 9101

spring:
   profiles:
     active: ${profileActive}
   application:
     name: webuy-message

logging:
  config: classpath:config/logback/logback-spring.xml


mybatis:
  config-location: classpath:config/mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.weweibuy.webuy.message.common.model.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件


