

spring:
   profiles:
     active: ${profileActive}
   application:
     name: webuy-gateway

logging:
  config: classpath:config/logback/logback-spring.xml


zuul:
  ignored-services: "*"  #忽略所有未配置的service
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
    backstage:
      path: /backstage/**
      strip-prefix: true  #忽略前缀
      sensitiveHeaders: #Cookie,Set-Cookie,Authorization
      serviceId: webuy-backstage
      add-host-header: true
    auth:
      path: /auth/**
      strip-prefix: true
      #  下面这个配置的作用一定要弄清楚; 如果不加在请求后面的auth服务时 basic登录无法成功;
      #  即使使用正确的参数访问 http://localhost:8080/auth/oauth/token; 也是返回401
      # 这里是因为zuul 使用  RibbonRoutingFilter(ProxyRequestHelper) 重新创建请求头  在创建时调用isIncludedHeader(name)方法
      # 将原请求的请求头复制到 RibbonRoutingFilter 创建的请求中, 下面的配置是创建时选择忽略的请求头默认是:Cookie,Set-Cookie,Authorization
      # 在调取/oauth/token 时经过  BasicAuthenticationFilter 验证 Authorization(client_id 和 client_secret) 由于无法验证client信息返回401
      sensitiveHeaders: #  加上后面这些也是返回401,什么都不加可RibbonRoutingFilter以正确返回 #Cookie,Set-Cookie,Authorization
      serviceId: webuy-auth  #转发到对应的 serviceID上
      add-host-header: true    # 此处解决后端服务重定向导致用户浏览的 host 变成 后端服务的 host 问题
    user:
      path: /user/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: webuy-user
      add-host-header: true


#负载均衡
webuy-backstage: #是serviceId
  ribbon:
    ServerListRefreshInterval: 10000  # Interval to refresh the server list from the source
    listOfServers: http://localhost:8001
    ConnectTimeout: 3000   #建立连接超时时间
    ReadTimeout: 5000  #连接超时时间
    OkToRetryOnAllOperations: true  #所有操作都重试
    MaxAutoRetries: 0  #单个节点重试最大值
    MaxAutoRetriesNextServer: 1   #重试发生，更换节点数最大值

webuy-auth: #是serviceId
  ribbon:
    ServerListRefreshInterval: 10000  # Interval to refresh the server list from the source
    listOfServers: http://localhost:8070
    ConnectTimeout: 3000   #建立连接超时时间
    ReadTimeout: 5000  #连接超时时间
    OkToRetryOnAllOperations: true  #所有操作都重试
    MaxAutoRetries: 0  #单个节点重试最大值
    MaxAutoRetriesNextServer: 1   #重试发生，更换节点数最大值

webuy-user: #是serviceId
  ribbon:
    ServerListRefreshInterval: 10000  # Interval to refresh the server list from the source
    listOfServers: http://localhost:8201
    ConnectTimeout: 3000   #建立连接超时时间
    ReadTimeout: 5000  #连接超时时间
    OkToRetryOnAllOperations: true  #所有操作都重试
    MaxAutoRetries: 0  #单个节点重试最大值
    MaxAutoRetriesNextServer: 1   #重试发生，更换节点数最大值