server:
  port: 80
  tomcat:
    max-threads: 10
    min-spare-threads: 5

spring:
  zipkin:
    base-url: http://106.12.95.245:9411
    enabled: true
    messageTimeout: 10
    discoveryClientEnabled: true
  sleuth:
    sampler:
      probability: 0.3 #收集比例
  security:
    user:
      name: admin
      password: ak402507979

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@47.99.129.104:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}  #必须唯一
    prefer-ip-address: true     #访问路径可以显示IP地址,此为内网ip,如果server和client不在同一网段使用ip-address:配置
    ip-address: 119.3.11.116
    metadata-map:
       context-path: /actuator
       startup: ${random.int}    #needed to trigger info and endpoint update after restart
       "user.name": admin         #These two are needed so that the server
       "user.password": ak402507979  #can access the protected client endpoints
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/

hystrix: #hystrix配置
  command:
    default:
      execution:
        timeout:
         enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        sleepWindowInMilliseconds: 20000 #断路器恢复时间
        errorThresholdPercentage: 50  #触发短路,失败百分比
  threadpool:
    default:
      coreSize: 10  #线程池大小
      maxQueueSize: 10  #最大等待队列数
      queueSizeRejectionThreshold: 5 #触发拒绝请求的的最大等待队列数
