server:
  port: 80
  tomcat:
    max-threads: 10
    min-spare-threads: 5

spring:
  zipkin:
    base-url: http://106.12.95.245:9411
    enabled: true
    messageTimeout: 10
    discoveryClientEnabled: true
  sleuth:
    sampler:
      probability: 0.5 #收集比例
  redis:
    timeout: 5000 # 连接超时时间（毫秒）
    database: 4 # Redis数据库索引（默认为0）
    host: 106.12.95.245  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: ak402507979 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 3 # 连接池中的最大空闲连接
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 2 # 连接池中的最小空闲连接

  cloud:
    gateway:
      routes:
#      - id: auth_0
#        uri: lb://webuy-auth  # lb 开头为 eureka 注册的实例
#        predicates:
#        - Path=/auth/** # Path 要大写
#        filters:
#        - StripPrefix=1 #忽略前缀 个数
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 2
#            redis-rate-limiter.burstCapacity: 4
#            key-resolver: "#{@apiKeyResolver}"
      - id: cnblogs
        uri: https://www.cnblogs.com
        predicates:
        - Path=/csdn/cnblogs/**
        filters:
        - StripPrefix=2
#      - id: learm-spring
#        uri: lb://learning-spring
#        predicates:
#        - Path=/learn-spring/**
#        filters:
#        - StripPrefix=1
#        - PrefixPath=/api/v1
#        - RewritePath=/learn-spring, /api/v1


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@106.12.95.245:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}  #必须唯一
    prefer-ip-address: true     #访问路径可以显示IP地址,此为内网ip,如果server和client不在同一网段使用ip-address:配置
    ip-address: 127.0.0.1
    metadata-map:
       context-path: /actuator
       startup: ${random.int}    #needed to trigger info and endpoint update after restart
       "user.name": admin         #These two are needed so that the server
       "user.password": ak402507979  #can access the protected client endpoints
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/

hystrix: #hystrix配置
  command:
    default:
      execution:
        timeout:
         enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        sleepWindowInMilliseconds: 1000 #断路器恢复时间
        errorThresholdPercentage: 80  #触发短路,失败百分比
    learn-spring:
      execution:
        timeout:
         enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        sleepWindowInMilliseconds: 1000 #断路器恢复时间
        errorThresholdPercentage: 80  #触发短路,失败百分比
  threadpool:
    default:
      coreSize: 10  #线程池大小
      maxQueueSize: 10  #最大等待队列数
      queueSizeRejectionThreshold: 5 #触发拒绝请求的的最大等待队列数


