

spring:
   profiles:
     active: ${profileActive}
   application:
     name: webuy-auth

logging:
  config: classpath:config/logback/logback-spring.xml


mybatis:
  config-location: classpath:config/mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.weweibuy.webuy.auth.model.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

webuy:
  auth:
    security:
      loginResponseType: JSON   #REDIRECT #JSON
      social:
        qq:
        #processesUrl: /qqLogin
        #providerId: callback.do
          app-id: 101386962
          app-security: 2a0f820407df400b84a854d054be8b6a
        weixin:
        #processesUrl: /qqLogin
        #providerId: weixin
          app-id: wxd99431bbff8305a0
          app-security: 60f78681d063590a469f1b297feff3c4